### ISSUE TITLE
for reverse but non reverse list of episodes

### ISSUE THREAD

**Issue by MparkG** [mashuptwice/spdl#1]
```
count = len(episodenames)
for i in episodenames:
        print(str(count) + ":  " + i)
        count -= 1
```

**Comment by MparkG** [comment]
nvm lol that seemed to create chaos

**Comment by mashuptwice** [comment]
Currently the problem is that the newest seasons page lists the episodes in descending order, while all other seasons are listed in ascending order.

Currently this is no more but an inconvenience, but I plan to add support for downloading multiple episodes in one pass and there it could be a bigger inconvenience. If you have any ideas to handle this case, please let me know!
